In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [9]:
n = int(input("Введите количество элементов массива Numpy: "))

my_np_ar = np.arange(0, n)
print (my_np_ar)

Введите количество элементов массива Numpy: 8
[0 1 2 3 4 5 6 7]


In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [17]:
x = np.diag(np.arange(n), k=0)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 6 0]
 [0 0 0 0 0 0 0 7]]


In [16]:
sum(np.diag(x))

28

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [21]:
M1 = np.array([[4., 2., 1.], [1., 3., 0.], [0., 5., 4.]]) # Матрица (левая часть системы)
v1 = np.array([4., 12., -3.]) # Вектор (правая часть системы)

# print(M1)
# print(v1)

In [22]:
np.linalg.solve(M1, v1)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
# Задание 4

In [4]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [5]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [72]:
def cosine( next_user_stats, i ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( next_user_stats )
    bLength = np.linalg.norm( i )
    
    return np.dot( next_user_stats, i ) / ( aLength * bLength )



In [76]:
cosine_list = []
for i in users_stats:
    cosine_list.append(cosine(next_user_stats,i))

cosine_array = np.array(cosine_list)

new_array = np.c_[users_stats,cosine_array]
sorted_array = sorted(new_array, key=lambda x : x[6],reverse = True)
print(sorted_array[0])

[0.        1.        1.        0.        0.        0.        0.9486833]
